---
# See https://github.com/jvautier/project-cli
fullname: jvautier/ansible-role-common
description: Install basics work through ansible
tags:
  - ansible
  - ansible-role
github:
  has_issues: true
  has_projects: false
  has_wiki: false
